`timescale 1 ns / 1 ps

module skinoc_v1_0 #
(
// Users to add parameters here

// User parameters ends
// Do not modify the parameters beyond this line


// Parameters of Axi Slave Bus Interface S00_AXI
parameter integer C_S00_AXI_ID_WIDTH = 1,
parameter integer C_S00_AXI_DATA_WIDTH = 32,
parameter integer C_S00_AXI_ADDR_WIDTH = 32,
parameter integer C_S00_AXI_AWUSER_WIDTH = 0,
parameter integer C_S00_AXI_ARUSER_WIDTH = 0,
parameter integer C_S00_AXI_WUSER_WIDTH = 0,
parameter integer C_S00_AXI_RUSER_WIDTH = 0,
parameter integer C_S00_AXI_BUSER_WIDTH = 0,

// Parameters of Axi Slave Bus Interface S01_AXI
parameter integer C_S01_AXI_ID_WIDTH = 1,
parameter integer C_S01_AXI_DATA_WIDTH = 32,
parameter integer C_S01_AXI_ADDR_WIDTH = 32,
parameter integer C_S01_AXI_AWUSER_WIDTH = 0,
parameter integer C_S01_AXI_ARUSER_WIDTH = 0,
parameter integer C_S01_AXI_WUSER_WIDTH = 0,
parameter integer C_S01_AXI_RUSER_WIDTH = 0,
parameter integer C_S01_AXI_BUSER_WIDTH = 0,

// Parameters of Axi Slave Bus Interface S02_AXI
parameter integer C_S02_AXI_ID_WIDTH = 1,
parameter integer C_S02_AXI_DATA_WIDTH = 32,
parameter integer C_S02_AXI_ADDR_WIDTH = 32,
parameter integer C_S02_AXI_AWUSER_WIDTH = 0,
parameter integer C_S02_AXI_ARUSER_WIDTH = 0,
parameter integer C_S02_AXI_WUSER_WIDTH = 0,
parameter integer C_S02_AXI_RUSER_WIDTH = 0,
parameter integer C_S02_AXI_BUSER_WIDTH = 0,

// Parameters of Axi Slave Bus Interface S03_AXI
parameter integer C_S03_AXI_ID_WIDTH = 1,
parameter integer C_S03_AXI_DATA_WIDTH = 32,
parameter integer C_S03_AXI_ADDR_WIDTH = 32,
parameter integer C_S03_AXI_AWUSER_WIDTH = 0,
parameter integer C_S03_AXI_ARUSER_WIDTH = 0,
parameter integer C_S03_AXI_WUSER_WIDTH = 0,
parameter integer C_S03_AXI_RUSER_WIDTH = 0,
parameter integer C_S03_AXI_BUSER_WIDTH = 0
)
(
// Users to add ports here

// User ports ends
// Do not modify the ports beyond this line
         input wire rst_n,
         input wire clk,
        // input wire [63:0]GTB1,
         input wire [63:0] GTB,
        

// Ports of Axi Slave Bus Interface S00_AXI
input wire  s00_axi_aclk,
input wire  s00_axi_aresetn,
input wire [C_S00_AXI_ID_WIDTH-1 : 0] s00_axi_awid,
input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_awaddr,
input wire [7 : 0] s00_axi_awlen,
input wire [2 : 0] s00_axi_awsize,
input wire [1 : 0] s00_axi_awburst,
input wire  s00_axi_awlock,
input wire [3 : 0] s00_axi_awcache,
input wire [2 : 0] s00_axi_awprot,
input wire [3 : 0] s00_axi_awqos,
input wire [3 : 0] s00_axi_awregion,
input wire [C_S00_AXI_AWUSER_WIDTH-1 : 0] s00_axi_awuser,
input wire  s00_axi_awvalid,
output wire  s00_axi_awready,
input wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_wdata,
input wire [(C_S00_AXI_DATA_WIDTH/8)-1 : 0] s00_axi_wstrb,
input wire  s00_axi_wlast,
input wire [C_S00_AXI_WUSER_WIDTH-1 : 0] s00_axi_wuser,
input wire  s00_axi_wvalid,
output wire  s00_axi_wready,
output wire [C_S00_AXI_ID_WIDTH-1 : 0] s00_axi_bid,
output wire [1 : 0] s00_axi_bresp,
output wire [C_S00_AXI_BUSER_WIDTH-1 : 0] s00_axi_buser,
output wire  s00_axi_bvalid,
input wire  s00_axi_bready,
input wire [C_S00_AXI_ID_WIDTH-1 : 0] s00_axi_arid,
input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_araddr,
input wire [7 : 0] s00_axi_arlen,
input wire [2 : 0] s00_axi_arsize,
input wire [1 : 0] s00_axi_arburst,
input wire  s00_axi_arlock,
input wire [3 : 0] s00_axi_arcache,
input wire [2 : 0] s00_axi_arprot,
input wire [3 : 0] s00_axi_arqos,
input wire [3 : 0] s00_axi_arregion,
input wire [C_S00_AXI_ARUSER_WIDTH-1 : 0] s00_axi_aruser,
input wire  s00_axi_arvalid,
output wire  s00_axi_arready,
output wire [C_S00_AXI_ID_WIDTH-1 : 0] s00_axi_rid,
output wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_rdata,
output wire [1 : 0] s00_axi_rresp,
output wire  s00_axi_rlast,
output wire [C_S00_AXI_RUSER_WIDTH-1 : 0] s00_axi_ruser,
output wire  s00_axi_rvalid,
input wire  s00_axi_rready,

// Ports of Axi Slave Bus Interface S01_AXI
input wire  s01_axi_aclk,
input wire  s01_axi_aresetn,
input wire [C_S01_AXI_ID_WIDTH-1 : 0] s01_axi_awid,
input wire [C_S01_AXI_ADDR_WIDTH-1 : 0] s01_axi_awaddr,
input wire [7 : 0] s01_axi_awlen,
input wire [2 : 0] s01_axi_awsize,
input wire [1 : 0] s01_axi_awburst,
input wire  s01_axi_awlock,
input wire [3 : 0] s01_axi_awcache,
input wire [2 : 0] s01_axi_awprot,
input wire [3 : 0] s01_axi_awqos,
input wire [3 : 0] s01_axi_awregion,
input wire [C_S01_AXI_AWUSER_WIDTH-1 : 0] s01_axi_awuser,
input wire  s01_axi_awvalid,
output wire  s01_axi_awready,
input wire [C_S01_AXI_DATA_WIDTH-1 : 0] s01_axi_wdata,
input wire [(C_S01_AXI_DATA_WIDTH/8)-1 : 0] s01_axi_wstrb,
input wire  s01_axi_wlast,
input wire [C_S01_AXI_WUSER_WIDTH-1 : 0] s01_axi_wuser,
input wire  s01_axi_wvalid,
output wire  s01_axi_wready,
output wire [C_S01_AXI_ID_WIDTH-1 : 0] s01_axi_bid,
output wire [1 : 0] s01_axi_bresp,
output wire [C_S01_AXI_BUSER_WIDTH-1 : 0] s01_axi_buser,
output wire  s01_axi_bvalid,
input wire  s01_axi_bready,
input wire [C_S01_AXI_ID_WIDTH-1 : 0] s01_axi_arid,
input wire [C_S01_AXI_ADDR_WIDTH-1 : 0] s01_axi_araddr,
input wire [7 : 0] s01_axi_arlen,
input wire [2 : 0] s01_axi_arsize,
input wire [1 : 0] s01_axi_arburst,
input wire  s01_axi_arlock,
input wire [3 : 0] s01_axi_arcache,
input wire [2 : 0] s01_axi_arprot,
input wire [3 : 0] s01_axi_arqos,
input wire [3 : 0] s01_axi_arregion,
input wire [C_S01_AXI_ARUSER_WIDTH-1 : 0] s01_axi_aruser,
input wire  s01_axi_arvalid,
output wire  s01_axi_arready,
output wire [C_S01_AXI_ID_WIDTH-1 : 0] s01_axi_rid,
output wire [C_S01_AXI_DATA_WIDTH-1 : 0] s01_axi_rdata,
output wire [1 : 0] s01_axi_rresp,
output wire  s01_axi_rlast,
output wire [C_S01_AXI_RUSER_WIDTH-1 : 0] s01_axi_ruser,
output wire  s01_axi_rvalid,
input wire  s01_axi_rready,

// Ports of Axi Slave Bus Interface S02_AXI
input wire  s02_axi_aclk,
input wire  s02_axi_aresetn,
input wire [C_S02_AXI_ID_WIDTH-1 : 0] s02_axi_awid,
input wire [C_S02_AXI_ADDR_WIDTH-1 : 0] s02_axi_awaddr,
input wire [7 : 0] s02_axi_awlen,
input wire [2 : 0] s02_axi_awsize,
input wire [1 : 0] s02_axi_awburst,
input wire  s02_axi_awlock,
input wire [3 : 0] s02_axi_awcache,
input wire [2 : 0] s02_axi_awprot,
input wire [3 : 0] s02_axi_awqos,
input wire [3 : 0] s02_axi_awregion,
input wire [C_S02_AXI_AWUSER_WIDTH-1 : 0] s02_axi_awuser,
input wire  s02_axi_awvalid,
output wire  s02_axi_awready,
input wire [C_S02_AXI_DATA_WIDTH-1 : 0] s02_axi_wdata,
input wire [(C_S02_AXI_DATA_WIDTH/8)-1 : 0] s02_axi_wstrb,
input wire  s02_axi_wlast,
input wire [C_S02_AXI_WUSER_WIDTH-1 : 0] s02_axi_wuser,
input wire  s02_axi_wvalid,
output wire  s02_axi_wready,
output wire [C_S02_AXI_ID_WIDTH-1 : 0] s02_axi_bid,
output wire [1 : 0] s02_axi_bresp,
output wire [C_S02_AXI_BUSER_WIDTH-1 : 0] s02_axi_buser,
output wire  s02_axi_bvalid,
input wire  s02_axi_bready,
input wire [C_S02_AXI_ID_WIDTH-1 : 0] s02_axi_arid,
input wire [C_S02_AXI_ADDR_WIDTH-1 : 0] s02_axi_araddr,
input wire [7 : 0] s02_axi_arlen,
input wire [2 : 0] s02_axi_arsize,
input wire [1 : 0] s02_axi_arburst,
input wire  s02_axi_arlock,
input wire [3 : 0] s02_axi_arcache,
input wire [2 : 0] s02_axi_arprot,
input wire [3 : 0] s02_axi_arqos,
input wire [3 : 0] s02_axi_arregion,
input wire [C_S02_AXI_ARUSER_WIDTH-1 : 0] s02_axi_aruser,
input wire  s02_axi_arvalid,
output wire  s02_axi_arready,
output wire [C_S02_AXI_ID_WIDTH-1 : 0] s02_axi_rid,
output wire [C_S02_AXI_DATA_WIDTH-1 : 0] s02_axi_rdata,
output wire [1 : 0] s02_axi_rresp,
output wire  s02_axi_rlast,
output wire [C_S02_AXI_RUSER_WIDTH-1 : 0] s02_axi_ruser,
output wire  s02_axi_rvalid,
input wire  s02_axi_rready,

// Ports of Axi Slave Bus Interface S03_AXI
input wire  s03_axi_aclk,
input wire  s03_axi_aresetn,
input wire [C_S03_AXI_ID_WIDTH-1 : 0] s03_axi_awid,
input wire [C_S03_AXI_ADDR_WIDTH-1 : 0] s03_axi_awaddr,
input wire [7 : 0] s03_axi_awlen,
input wire [2 : 0] s03_axi_awsize,
input wire [1 : 0] s03_axi_awburst,
input wire  s03_axi_awlock,
input wire [3 : 0] s03_axi_awcache,
input wire [2 : 0] s03_axi_awprot,
input wire [3 : 0] s03_axi_awqos,
input wire [3 : 0] s03_axi_awregion,
input wire [C_S03_AXI_AWUSER_WIDTH-1 : 0] s03_axi_awuser,
input wire  s03_axi_awvalid,
output wire  s03_axi_awready,
input wire [C_S03_AXI_DATA_WIDTH-1 : 0] s03_axi_wdata,
input wire [(C_S03_AXI_DATA_WIDTH/8)-1 : 0] s03_axi_wstrb,
input wire  s03_axi_wlast,
input wire [C_S03_AXI_WUSER_WIDTH-1 : 0] s03_axi_wuser,
input wire  s03_axi_wvalid,
output wire  s03_axi_wready,
output wire [C_S03_AXI_ID_WIDTH-1 : 0] s03_axi_bid,
output wire [1 : 0] s03_axi_bresp,
output wire [C_S03_AXI_BUSER_WIDTH-1 : 0] s03_axi_buser,
output wire  s03_axi_bvalid,
input wire  s03_axi_bready,
input wire [C_S03_AXI_ID_WIDTH-1 : 0] s03_axi_arid,
input wire [C_S03_AXI_ADDR_WIDTH-1 : 0] s03_axi_araddr,
input wire [7 : 0] s03_axi_arlen,
input wire [2 : 0] s03_axi_arsize,
input wire [1 : 0] s03_axi_arburst,
input wire  s03_axi_arlock,
input wire [3 : 0] s03_axi_arcache,
input wire [2 : 0] s03_axi_arprot,
input wire [3 : 0] s03_axi_arqos,
input wire [3 : 0] s03_axi_arregion,
input wire [C_S03_AXI_ARUSER_WIDTH-1 : 0] s03_axi_aruser,
input wire  s03_axi_arvalid,
output wire  s03_axi_arready,
output wire [C_S03_AXI_ID_WIDTH-1 : 0] s03_axi_rid,
output wire [C_S03_AXI_DATA_WIDTH-1 : 0] s03_axi_rdata,
output wire [1 : 0] s03_axi_rresp,
output wire  s03_axi_rlast,
output wire [C_S03_AXI_RUSER_WIDTH-1 : 0] s03_axi_ruser,
output wire  s03_axi_rvalid,
input wire  s03_axi_rready
);




torus_mesh mm(
                   .rst_n (rst_n),
                   .clk (clk),
                   .GTB(GTB),
                 //  .GTB1 (GTB1),
                  .s_axi_core_awid_0           (   s00_axi_awid  ) ,  
                  .s_axi_core_awaddr_0         (   s00_axi_awaddr  ) ,
                  .s_axi_core_awlen_0          (   s00_axi_awlen  ) ,
                  .s_axi_core_awsize_0         (   s00_axi_awsize  ) ,
                  .s_axi_core_awburst_0        (   s00_axi_awburst  ) ,
                  .s_axi_core_awlock_0         (   s00_axi_awlock  ) ,
                  .s_axi_core_awcache_0        (   s00_axi_awcache  ) ,
                  .s_axi_core_awprot_0         (   s00_axi_awprot  ) ,
                  .s_axi_core_awqos_0          (   s00_axi_awqos  ) ,
                  .s_axi_core_awregion_0       (   s00_axi_awregion  ) ,
                  .s_axi_core_awuser_0         (   s00_axi_awuser  ) ,
                  .s_axi_core_awvalid_0        (   s00_axi_awvalid  ) ,
                  .s_axi_core_awready_0        (   s00_axi_awready  ) ,
                  .s_axi_core_wdata_0          (   s00_axi_wdata  ) ,
                  .s_axi_core_wstrb_0          (   s00_axi_wstrb  ) ,
                  .s_axi_core_wlast_0          (   s00_axi_wlast  ) ,
                  .s_axi_core_wuser_0          (   s00_axi_wuser  ) ,
                  .s_axi_core_wvalid_0         (   s00_axi_wvalid  ) ,
                  .s_axi_core_wready_0         (   s00_axi_wready  ) ,
                  .s_axi_core_bid_0            (   s00_axi_bid  ) ,
                  .s_axi_core_bresp_0          (   s00_axi_bresp  ) ,
                  .s_axi_core_buser_0          (   s00_axi_buser  ) ,
                  .s_axi_core_bvalid_0         (   s00_axi_bvalid  ) ,
                  .s_axi_core_bready_0         (   s00_axi_bready  ) ,
                  .s_axi_core_arid_0           (   s00_axi_arid  ) ,
                  .s_axi_core_araddr_0         (   s00_axi_araddr  ) ,
                  .s_axi_core_arlen_0          (   s00_axi_arlen  ) ,
                  .s_axi_core_arsize_0         (   s00_axi_arsize  ) ,
                  .s_axi_core_arburst_0        (   s00_axi_arburst  ) ,
                  .s_axi_core_arlock_0         (   s00_axi_arlock  ) ,
                  .s_axi_core_arcache_0        (   s00_axi_arcache  ) ,
                  .s_axi_core_arprot_0         (   s00_axi_arprot  ) ,
                  .s_axi_core_arqos_0          (   s00_axi_arqos  ) ,
                  .s_axi_core_arregion_0       (   s00_axi_arregion  ) ,
                  .s_axi_core_aruser_0         (   s00_axi_aruser  ) ,
                  .s_axi_core_arvalid_0        (   s00_axi_arvalid  ) ,
                  .s_axi_core_arready_0        (   s00_axi_arready  ) ,
                  .s_axi_core_rid_0            (   s00_axi_rid  ) ,
                  .s_axi_core_rdata_0          (   s00_axi_rdata  ) ,
                  .s_axi_core_rresp_0          (   s00_axi_rresp  ) ,
                  .s_axi_core_rlast_0          (   s00_axi_rlast  ) ,
                  .s_axi_core_ruser_0          (   s00_axi_ruser  ) ,
                  .s_axi_core_rvalid_0         (   s00_axi_rvalid  ) ,
                  .s_axi_core_rready_0         (   s00_axi_rready  ) ,
                  .s_axi_core_awid_1           (   s01_axi_awid  ) ,  
                  .s_axi_core_awaddr_1         (   s01_axi_awaddr  ) ,
                  .s_axi_core_awlen_1          (   s01_axi_awlen  ) ,
                  .s_axi_core_awsize_1         (   s01_axi_awsize  ) ,
                  .s_axi_core_awburst_1        (   s01_axi_awburst  ) ,
                  .s_axi_core_awlock_1         (   s01_axi_awlock  ) ,
                  .s_axi_core_awcache_1        (   s01_axi_awcache  ) ,
                  .s_axi_core_awprot_1         (   s01_axi_awprot  ) ,
                  .s_axi_core_awqos_1          (   s01_axi_awqos  ) ,
                  .s_axi_core_awregion_1       (   s01_axi_awregion  ) ,
                  .s_axi_core_awuser_1         (   s01_axi_awuser  ) ,
                  .s_axi_core_awvalid_1        (   s01_axi_awvalid  ) ,
                  .s_axi_core_awready_1        (   s01_axi_awready  ) ,
                  .s_axi_core_wdata_1          (   s01_axi_wdata  ) ,
                  .s_axi_core_wstrb_1          (   s01_axi_wstrb  ) ,
                  .s_axi_core_wlast_1          (   s01_axi_wlast  ) ,
                  .s_axi_core_wuser_1          (   s01_axi_wuser  ) ,
                  .s_axi_core_wvalid_1         (   s01_axi_wvalid  ) ,
                  .s_axi_core_wready_1         (   s01_axi_wready  ) ,
                  .s_axi_core_bid_1            (   s01_axi_bid  ) ,
                  .s_axi_core_bresp_1          (   s01_axi_bresp  ) ,
                  .s_axi_core_buser_1          (   s01_axi_buser  ) ,
                  .s_axi_core_bvalid_1         (   s01_axi_bvalid  ) ,
                  .s_axi_core_bready_1         (   s01_axi_bready  ) ,
                  .s_axi_core_arid_1           (   s01_axi_arid  ) ,
                  .s_axi_core_araddr_1         (   s01_axi_araddr  ) ,
                  .s_axi_core_arlen_1          (   s01_axi_arlen  ) ,
                  .s_axi_core_arsize_1         (   s01_axi_arsize  ) ,
                  .s_axi_core_arburst_1        (   s01_axi_arburst  ) ,
                  .s_axi_core_arlock_1         (   s01_axi_arlock  ) ,
                  .s_axi_core_arcache_1        (   s01_axi_arcache  ) ,
                  .s_axi_core_arprot_1         (   s01_axi_arprot  ) ,
                  .s_axi_core_arqos_1          (   s01_axi_arqos  ) ,
                  .s_axi_core_arregion_1       (   s01_axi_arregion  ) ,
                  .s_axi_core_aruser_1         (   s01_axi_aruser  ) ,
                  .s_axi_core_arvalid_1        (   s01_axi_arvalid  ) ,
                  .s_axi_core_arready_1        (   s01_axi_arready  ) ,
                  .s_axi_core_rid_1            (   s01_axi_rid  ) ,
                  .s_axi_core_rdata_1          (   s01_axi_rdata  ) ,
                  .s_axi_core_rresp_1          (   s01_axi_rresp  ) ,
                  .s_axi_core_rlast_1          (   s01_axi_rlast  ) ,
                  .s_axi_core_ruser_1          (   s01_axi_ruser  ) ,
                  .s_axi_core_rvalid_1         (   s01_axi_rvalid  ) ,
                  .s_axi_core_rready_1         (   s01_axi_rready  ) ,
   
   
   
   
   
  
                  .s_axi_core_awid_2           (   s02_axi_awid  ) ,  
                  .s_axi_core_awaddr_2         (   s02_axi_awaddr  ) ,
                  .s_axi_core_awlen_2          (   s02_axi_awlen  ) ,
                  .s_axi_core_awsize_2         (   s02_axi_awsize  ) ,
                  .s_axi_core_awburst_2        (   s02_axi_awburst  ) ,
                  .s_axi_core_awlock_2         (   s02_axi_awlock  ) ,
                  .s_axi_core_awcache_2        (   s02_axi_awcache  ) ,
                  .s_axi_core_awprot_2         (   s02_axi_awprot  ) ,
                  .s_axi_core_awqos_2          (   s02_axi_awqos  ) ,
                  .s_axi_core_awregion_2       (   s02_axi_awregion  ) ,
                  .s_axi_core_awuser_2         (   s02_axi_awuser  ) ,
                  .s_axi_core_awvalid_2        (   s02_axi_awvalid  ) ,
                  .s_axi_core_awready_2        (   s02_axi_awready  ) ,
                  .s_axi_core_wdata_2          (   s02_axi_wdata  ) ,
                  .s_axi_core_wstrb_2          (   s02_axi_wstrb  ) ,
                  .s_axi_core_wlast_2          (   s02_axi_wlast  ) ,
                  .s_axi_core_wuser_2          (   s02_axi_wuser  ) ,
                  .s_axi_core_wvalid_2         (   s02_axi_wvalid  ) ,
                  .s_axi_core_wready_2         (   s02_axi_wready  ) ,
                  .s_axi_core_bid_2            (   s02_axi_bid  ) ,
                  .s_axi_core_bresp_2          (   s02_axi_bresp  ) ,
                  .s_axi_core_buser_2          (   s02_axi_buser  ) ,
                  .s_axi_core_bvalid_2         (   s02_axi_bvalid  ) ,
                  .s_axi_core_bready_2         (   s02_axi_bready  ) ,
                  .s_axi_core_arid_2           (   s02_axi_arid  ) ,
                  .s_axi_core_araddr_2         (   s02_axi_araddr  ) ,
                  .s_axi_core_arlen_2          (   s02_axi_arlen  ) ,
                  .s_axi_core_arsize_2         (   s02_axi_arsize  ) ,
                  .s_axi_core_arburst_2        (   s02_axi_arburst  ) ,
                  .s_axi_core_arlock_2         (   s02_axi_arlock  ) ,
                  .s_axi_core_arcache_2        (   s02_axi_arcache  ) ,
                  .s_axi_core_arprot_2         (   s02_axi_arprot  ) ,
                  .s_axi_core_arqos_2          (   s02_axi_arqos  ) ,
                  .s_axi_core_arregion_2       (   s02_axi_arregion  ) ,
                  .s_axi_core_aruser_2         (   s02_axi_aruser  ) ,
                  .s_axi_core_arvalid_2        (   s02_axi_arvalid  ) ,
                  .s_axi_core_arready_2        (   s02_axi_arready  ) ,
                  .s_axi_core_rid_2            (   s02_axi_rid  ) ,
                  .s_axi_core_rdata_2          (   s02_axi_rdata  ) ,
                  .s_axi_core_rresp_2          (   s02_axi_rresp  ) ,
                  .s_axi_core_rlast_2          (   s02_axi_rlast  ) ,
                  .s_axi_core_ruser_2          (   s02_axi_ruser  ) ,
                  .s_axi_core_rvalid_2         (   s02_axi_rvalid  ) ,
                  .s_axi_core_rready_2         (   s02_axi_rready  ) ,
  
  
  
  
  
  
                  .s_axi_core_awid_3           (   s03_axi_awid  ) ,  
                  .s_axi_core_awaddr_3         (   s03_axi_awaddr  ) ,
                  .s_axi_core_awlen_3          (   s03_axi_awlen  ) ,
                  .s_axi_core_awsize_3         (   s03_axi_awsize  ) ,
                  .s_axi_core_awburst_3        (   s03_axi_awburst  ) ,
                  .s_axi_core_awlock_3         (   s03_axi_awlock  ) ,
                  .s_axi_core_awcache_3        (   s03_axi_awcache  ) ,
                  .s_axi_core_awprot_3         (   s03_axi_awprot  ) ,
                  .s_axi_core_awqos_3          (   s03_axi_awqos  ) ,
                  .s_axi_core_awregion_3       (   s03_axi_awregion  ) ,
                  .s_axi_core_awuser_3         (   s03_axi_awuser  ) ,
                  .s_axi_core_awvalid_3        (   s03_axi_awvalid  ) ,
                  .s_axi_core_awready_3        (   s03_axi_awready  ) ,
                  .s_axi_core_wdata_3          (   s03_axi_wdata  ) ,
                  .s_axi_core_wstrb_3          (   s03_axi_wstrb  ) ,
                  .s_axi_core_wlast_3          (   s03_axi_wlast  ) ,
                  .s_axi_core_wuser_3          (   s03_axi_wuser  ) ,
                  .s_axi_core_wvalid_3         (   s03_axi_wvalid  ) ,
                  .s_axi_core_wready_3         (   s03_axi_wready  ) ,
                  .s_axi_core_bid_3            (   s03_axi_bid  ) ,
                  .s_axi_core_bresp_3          (   s03_axi_bresp  ) ,
                  .s_axi_core_buser_3          (   s03_axi_buser  ) ,
                  .s_axi_core_bvalid_3         (   s03_axi_bvalid  ) ,
                  .s_axi_core_bready_3         (   s03_axi_bready  ) ,
                  .s_axi_core_arid_3           (   s03_axi_arid  ) ,
                  .s_axi_core_araddr_3         (   s03_axi_araddr  ) ,
                  .s_axi_core_arlen_3          (   s03_axi_arlen  ) ,
                  .s_axi_core_arsize_3         (   s03_axi_arsize  ) ,
                  .s_axi_core_arburst_3        (   s03_axi_arburst  ) ,
                  .s_axi_core_arlock_3         (   s03_axi_arlock  ) ,
                  .s_axi_core_arcache_3        (   s03_axi_arcache  ) ,
                  .s_axi_core_arprot_3         (   s03_axi_arprot  ) ,
                  .s_axi_core_arqos_3          (   s03_axi_arqos  ) ,
                  .s_axi_core_arregion_3       (   s03_axi_arregion  ) ,
                  .s_axi_core_aruser_3         (   s03_axi_aruser  ) ,
                  .s_axi_core_arvalid_3        (   s03_axi_arvalid  ) ,
                  .s_axi_core_arready_3        (   s03_axi_arready  ) ,
                  .s_axi_core_rid_3            (   s03_axi_rid  ) ,
                  .s_axi_core_rdata_3          (   s03_axi_rdata  ) ,
                  .s_axi_core_rresp_3          (   s03_axi_rresp  ) ,
                  .s_axi_core_rlast_3          (   s03_axi_rlast  ) ,
                  .s_axi_core_ruser_3          (   s03_axi_ruser  ) ,
                  .s_axi_core_rvalid_3         (   s03_axi_rvalid  ) ,
                  .s_axi_core_rready_3         (   s03_axi_rready  ) 
                   
                   
              );


endmodule
